services:
  - name: web
    env:
      PORT: 8080
    dockerfile: Dockerfile
    healthCheck:
      http:
        path: /
        port: 8080
        statusCode: 200
build:
  command: pip install -r requirements.txt
start:
  command: python app.py